### ISSUE TITLE
where is the Optimization Step in the code?

### ISSUE THREAD

**Issue by WUKUNTAI-0211** [vidit09/domaingen#1]
Thank you for the great works! However, I couldn't find the Optimization Step in the code. Can you provide more context or point me to the specific section where the Optimization Step is supposed to be implemented?

**Comment by vidit09** [comment]
Hello, thanks for your interest. 
You can find the optimization function [here](  https://github.com/vidit09/domaingen/blob/9c03d07a6f8c12b6a7a5e02bd9346d7bb5a3b9ff/modeling/meta_arch.py#L234) in  modeling/meta_arch.py . This function is called inside [train.py ](https://github.com/vidit09/domaingen/blob/9c03d07a6f8c12b6a7a5e02bd9346d7bb5a3b9ff/train.py#L302). We run optimization step for  OFFSET_OPT_ITERS number of iterations before starting model training.
