### ISSUE TITLE
Va and Vb in the saved pth file

### ISSUE THREAD

**Issue by ParthT25** [vidit09/domaingen#10]
Hello @vidit09,

In the saved .pth file of the model what are the weights of  Va and Vb which are actually trained in the training phase?

**Comment by vidit09** [comment]
Hello,
So Va and Vb are different ResNet blocks. Va- ResNet until block3 and Vb - ResNet Block4+attn layer. So the weights are not separately store but rather in the code , we have output of [forward function](https://github.com/vidit09/domaingen/blob/9c03d07a6f8c12b6a7a5e02bd9346d7bb5a3b9ff/modeling/backbone.py#L31) as Va and Vb is computed through [1](https://github.com/vidit09/domaingen/blob/9c03d07a6f8c12b6a7a5e02bd9346d7bb5a3b9ff/modeling/backbone.py#L64) and [2](https://github.com/vidit09/domaingen/blob/9c03d07a6f8c12b6a7a5e02bd9346d7bb5a3b9ff/modeling/backbone.py#L68)

**Comment by ParthT25** [comment]
But in the paper you have mentioned that resnet 1-3 blocks are Va and resnet 4+attn as vb
![clip](https://github.com/vidit09/domaingen/assets/62347615/5c42f1a7-5298-4107-811c-046fb632c5b8)
and block 3,4 and attn are learned

**Comment by ParthT25** [comment]
so, from the pth file i am assuming 
following keys of the dict are the keys for the weights of va:
backbone.enc.conv1.weight
backbone.enc.bn1.weight
backbone.enc.bn1.bias
backbone.enc.bn1.running_mean
backbone.enc.bn1.running_var
backbone.enc.bn1.num_batches_tracked
backbone.enc.conv2.weight
backbone.enc.bn2.weight
backbone.enc.bn2.bias
backbone.enc.bn2.running_mean
backbone.enc.bn2.running_var
backbone.enc.bn2.num_batches_tracked
backbone.enc.conv3.weight
backbone.enc.bn3.weight
backbone.enc.bn3.bias
backbone.enc.bn3.running_mean
backbone.enc.bn3.running_var
backbone.enc.bn3.num_batches_tracked
backbone.enc.layer1.0.conv1.weight
backbone.enc.layer1.0.bn1.weight
backbone.enc.layer1.0.bn1.bias
backbone.enc.layer1.0.bn1.running_mean
backbone.enc.layer1.0.bn1.running_var
backbone.enc.layer1.0.bn1.num_batches_tracked
backbone.enc.layer1.0.conv2.weight
backbone.enc.layer1.0.bn2.weight
backbone.enc.layer1.0.bn2.bias
backbone.enc.layer1.0.bn2.running_mean
backbone.enc.layer1.0.bn2.running_var
backbone.enc.layer1.0.bn2.num_batches_tracked
backbone.enc.layer1.0.conv3.weight
backbone.enc.layer1.0.bn3.weight
backbone.enc.layer1.0.bn3.bias
backbone.enc.layer1.0.bn3.running_mean
backbone.enc.layer1.0.bn3.running_var
backbone.enc.layer1.0.bn3.num_batches_tracked
backbone.enc.layer1.0.downsample.0.weight
backbone.enc.layer1.0.downsample.1.weight
backbone.enc.layer1.0.downsample.1.bias
backbone.enc.layer1.0.downsample.1.running_mean
backbone.enc.layer1.0.downsample.1.running_var
backbone.enc.layer1.0.downsample.1.num_batches_tracked
backbone.enc.layer1.1.conv1.weight
backbone.enc.layer1.1.bn1.weight
backbone.enc.layer1.1.bn1.bias
backbone.enc.layer1.1.bn1.running_mean
backbone.enc.layer1.1.bn1.running_var
backbone.enc.layer1.1.bn1.num_batches_tracked
backbone.enc.layer1.1.conv2.weight
backbone.enc.layer1.1.bn2.weight
backbone.enc.layer1.1.bn2.bias
backbone.enc.layer1.1.bn2.running_mean
backbone.enc.layer1.1.bn2.running_var
backbone.enc.layer1.1.bn2.num_batches_tracked
backbone.enc.layer1.1.conv3.weight
backbone.enc.layer1.1.bn3.weight
backbone.enc.layer1.1.bn3.bias
backbone.enc.layer1.1.bn3.running_mean
backbone.enc.layer1.1.bn3.running_var
backbone.enc.layer1.1.bn3.num_batches_tracked
backbone.enc.layer1.2.conv1.weight
backbone.enc.layer1.2.bn1.weight
backbone.enc.layer1.2.bn1.bias
backbone.enc.layer1.2.bn1.running_mean
backbone.enc.layer1.2.bn1.running_var
backbone.enc.layer1.2.bn1.num_batches_tracked
backbone.enc.layer1.2.conv2.weight
backbone.enc.layer1.2.bn2.weight
backbone.enc.layer1.2.bn2.bias
backbone.enc.layer1.2.bn2.running_mean
backbone.enc.layer1.2.bn2.running_var
backbone.enc.layer1.2.bn2.num_batches_tracked
backbone.enc.layer1.2.conv3.weight
backbone.enc.layer1.2.bn3.weight
backbone.enc.layer1.2.bn3.bias
backbone.enc.layer1.2.bn3.running_mean
backbone.enc.layer1.2.bn3.running_var
backbone.enc.layer1.2.bn3.num_batches_tracked
backbone.enc.layer2.0.conv1.weight
backbone.enc.layer2.0.bn1.weight
backbone.enc.layer2.0.bn1.bias
backbone.enc.layer2.0.bn1.running_mean
backbone.enc.layer2.0.bn1.running_var
backbone.enc.layer2.0.bn1.num_batches_tracked
backbone.enc.layer2.0.conv2.weight
backbone.enc.layer2.0.bn2.weight
backbone.enc.layer2.0.bn2.bias
backbone.enc.layer2.0.bn2.running_mean
backbone.enc.layer2.0.bn2.running_var
backbone.enc.layer2.0.bn2.num_batches_tracked
backbone.enc.layer2.0.conv3.weight
backbone.enc.layer2.0.bn3.weight
backbone.enc.layer2.0.bn3.bias
backbone.enc.layer2.0.bn3.running_mean
backbone.enc.layer2.0.bn3.running_var
backbone.enc.layer2.0.bn3.num_batches_tracked
backbone.enc.layer2.0.downsample.0.weight
backbone.enc.layer2.0.downsample.1.weight
backbone.enc.layer2.0.downsample.1.bias
backbone.enc.layer2.0.downsample.1.running_mean
backbone.enc.layer2.0.downsample.1.running_var
backbone.enc.layer2.0.downsample.1.num_batches_tracked
backbone.enc.layer2.1.conv1.weight
backbone.enc.layer2.1.bn1.weight
backbone.enc.layer2.1.bn1.bias
backbone.enc.layer2.1.bn1.running_mean
backbone.enc.layer2.1.bn1.running_var
backbone.enc.layer2.1.bn1.num_batches_tracked
backbone.enc.layer2.1.conv2.weight
backbone.enc.layer2.1.bn2.weight
backbone.enc.layer2.1.bn2.bias
backbone.enc.layer2.1.bn2.running_mean
backbone.enc.layer2.1.bn2.running_var
backbone.enc.layer2.1.bn2.num_batches_tracked
backbone.enc.layer2.1.conv3.weight
backbone.enc.layer2.1.bn3.weight
backbone.enc.layer2.1.bn3.bias
backbone.enc.layer2.1.bn3.running_mean
backbone.enc.layer2.1.bn3.running_var
backbone.enc.layer2.1.bn3.num_batches_tracked
backbone.enc.layer2.2.conv1.weight
backbone.enc.layer2.2.bn1.weight
backbone.enc.layer2.2.bn1.bias
backbone.enc.layer2.2.bn1.running_mean
backbone.enc.layer2.2.bn1.running_var
backbone.enc.layer2.2.bn1.num_batches_tracked
backbone.enc.layer2.2.conv2.weight
backbone.enc.layer2.2.bn2.weight
backbone.enc.layer2.2.bn2.bias
backbone.enc.layer2.2.bn2.running_mean
backbone.enc.layer2.2.bn2.running_var
backbone.enc.layer2.2.bn2.num_batches_tracked
backbone.enc.layer2.2.conv3.weight
backbone.enc.layer2.2.bn3.weight
backbone.enc.layer2.2.bn3.bias
backbone.enc.layer2.2.bn3.running_mean
backbone.enc.layer2.2.bn3.running_var
backbone.enc.layer2.2.bn3.num_batches_tracked
backbone.enc.layer2.3.conv1.weight
backbone.enc.layer2.3.bn1.weight
backbone.enc.layer2.3.bn1.bias
backbone.enc.layer2.3.bn1.running_mean
backbone.enc.layer2.3.bn1.running_var
backbone.enc.layer2.3.bn1.num_batches_tracked
backbone.enc.layer2.3.conv2.weight
backbone.enc.layer2.3.bn2.weight
backbone.enc.layer2.3.bn2.bias
backbone.enc.layer2.3.bn2.running_mean
backbone.enc.layer2.3.bn2.running_var
backbone.enc.layer2.3.bn2.num_batches_tracked
backbone.enc.layer2.3.conv3.weight
backbone.enc.layer2.3.bn3.weight
backbone.enc.layer2.3.bn3.bias
backbone.enc.layer2.3.bn3.running_mean
backbone.enc.layer2.3.bn3.running_var
backbone.enc.layer2.3.bn3.num_batches_tracked
backbone.enc.layer3.0.conv1.weight
backbone.enc.layer3.0.bn1.weight
backbone.enc.layer3.0.bn1.bias
backbone.enc.layer3.0.bn1.running_mean
backbone.enc.layer3.0.bn1.running_var
backbone.enc.layer3.0.bn1.num_batches_tracked
backbone.enc.layer3.0.conv2.weight
backbone.enc.layer3.0.bn2.weight
backbone.enc.layer3.0.bn2.bias
backbone.enc.layer3.0.bn2.running_mean
backbone.enc.layer3.0.bn2.running_var
backbone.enc.layer3.0.bn2.num_batches_tracked
backbone.enc.layer3.0.conv3.weight
backbone.enc.layer3.0.bn3.weight
backbone.enc.layer3.0.bn3.bias
backbone.enc.layer3.0.bn3.running_mean
backbone.enc.layer3.0.bn3.running_var
backbone.enc.layer3.0.bn3.num_batches_tracked
backbone.enc.layer3.0.downsample.0.weight
backbone.enc.layer3.0.downsample.1.weight
backbone.enc.layer3.0.downsample.1.bias
backbone.enc.layer3.0.downsample.1.running_mean
backbone.enc.layer3.0.downsample.1.running_var
backbone.enc.layer3.0.downsample.1.num_batches_tracked
backbone.enc.layer3.1.conv1.weight
backbone.enc.layer3.1.bn1.weight
backbone.enc.layer3.1.bn1.bias
backbone.enc.layer3.1.bn1.running_mean
backbone.enc.layer3.1.bn1.running_var
backbone.enc.layer3.1.bn1.num_batches_tracked
backbone.enc.layer3.1.conv2.weight
backbone.enc.layer3.1.bn2.weight
backbone.enc.layer3.1.bn2.bias
backbone.enc.layer3.1.bn2.running_mean
backbone.enc.layer3.1.bn2.running_var
backbone.enc.layer3.1.bn2.num_batches_tracked
backbone.enc.layer3.1.conv3.weight
backbone.enc.layer3.1.bn3.weight
backbone.enc.layer3.1.bn3.bias
backbone.enc.layer3.1.bn3.running_mean
backbone.enc.layer3.1.bn3.running_var
backbone.enc.layer3.1.bn3.num_batches_tracked
backbone.enc.layer3.2.conv1.weight
backbone.enc.layer3.2.bn1.weight
backbone.enc.layer3.2.bn1.bias
backbone.enc.layer3.2.bn1.running_mean
backbone.enc.layer3.2.bn1.running_var
backbone.enc.layer3.2.bn1.num_batches_tracked
backbone.enc.layer3.2.conv2.weight
backbone.enc.layer3.2.bn2.weight
backbone.enc.layer3.2.bn2.bias
backbone.enc.layer3.2.bn2.running_mean
backbone.enc.layer3.2.bn2.running_var
backbone.enc.layer3.2.bn2.num_batches_tracked
backbone.enc.layer3.2.conv3.weight
backbone.enc.layer3.2.bn3.weight
backbone.enc.layer3.2.bn3.bias
backbone.enc.layer3.2.bn3.running_mean
backbone.enc.layer3.2.bn3.running_var
backbone.enc.layer3.2.bn3.num_batches_tracked
backbone.enc.layer3.3.conv1.weight
backbone.enc.layer3.3.bn1.weight
backbone.enc.layer3.3.bn1.bias
backbone.enc.layer3.3.bn1.running_mean
backbone.enc.layer3.3.bn1.running_var
backbone.enc.layer3.3.bn1.num_batches_tracked
backbone.enc.layer3.3.conv2.weight
backbone.enc.layer3.3.bn2.weight
backbone.enc.layer3.3.bn2.bias
backbone.enc.layer3.3.bn2.running_mean
backbone.enc.layer3.3.bn2.running_var
backbone.enc.layer3.3.bn2.num_batches_tracked
backbone.enc.layer3.3.conv3.weight
backbone.enc.layer3.3.bn3.weight
backbone.enc.layer3.3.bn3.bias
backbone.enc.layer3.3.bn3.running_mean
backbone.enc.layer3.3.bn3.running_var
backbone.enc.layer3.3.bn3.num_batches_tracked
backbone.enc.layer3.4.conv1.weight
backbone.enc.layer3.4.bn1.weight
backbone.enc.layer3.4.bn1.bias
backbone.enc.layer3.4.bn1.running_mean
backbone.enc.layer3.4.bn1.running_var
backbone.enc.layer3.4.bn1.num_batches_tracked
backbone.enc.layer3.4.conv2.weight
backbone.enc.layer3.4.bn2.weight
backbone.enc.layer3.4.bn2.bias
backbone.enc.layer3.4.bn2.running_mean
backbone.enc.layer3.4.bn2.running_var
backbone.enc.layer3.4.bn2.num_batches_tracked
backbone.enc.layer3.4.conv3.weight
backbone.enc.layer3.4.bn3.weight
backbone.enc.layer3.4.bn3.bias
backbone.enc.layer3.4.bn3.running_mean
backbone.enc.layer3.4.bn3.running_var
backbone.enc.layer3.4.bn3.num_batches_tracked
backbone.enc.layer3.5.conv1.weight
backbone.enc.layer3.5.bn1.weight
backbone.enc.layer3.5.bn1.bias
backbone.enc.layer3.5.bn1.running_mean
backbone.enc.layer3.5.bn1.running_var
backbone.enc.layer3.5.bn1.num_batches_tracked
backbone.enc.layer3.5.conv2.weight
backbone.enc.layer3.5.bn2.weight
backbone.enc.layer3.5.bn2.bias
backbone.enc.layer3.5.bn2.running_mean
backbone.enc.layer3.5.bn2.running_var
backbone.enc.layer3.5.bn2.num_batches_tracked
backbone.enc.layer3.5.conv3.weight
backbone.enc.layer3.5.bn3.weight
backbone.enc.layer3.5.bn3.bias
backbone.enc.layer3.5.bn3.running_mean
backbone.enc.layer3.5.bn3.running_var
backbone.enc.layer3.5.bn3.num_batches_tracked
backbone.enc.layer3.6.conv1.weight
backbone.enc.layer3.6.bn1.weight
backbone.enc.layer3.6.bn1.bias
backbone.enc.layer3.6.bn1.running_mean
backbone.enc.layer3.6.bn1.running_var
backbone.enc.layer3.6.bn1.num_batches_tracked
backbone.enc.layer3.6.conv2.weight
backbone.enc.layer3.6.bn2.weight
backbone.enc.layer3.6.bn2.bias
backbone.enc.layer3.6.bn2.running_mean
backbone.enc.layer3.6.bn2.running_var
backbone.enc.layer3.6.bn2.num_batches_tracked
backbone.enc.layer3.6.conv3.weight
backbone.enc.layer3.6.bn3.weight
backbone.enc.layer3.6.bn3.bias
backbone.enc.layer3.6.bn3.running_mean
backbone.enc.layer3.6.bn3.running_var
backbone.enc.layer3.6.bn3.num_batches_tracked
backbone.enc.layer3.7.conv1.weight
backbone.enc.layer3.7.bn1.weight
backbone.enc.layer3.7.bn1.bias
backbone.enc.layer3.7.bn1.running_mean
backbone.enc.layer3.7.bn1.running_var
backbone.enc.layer3.7.bn1.num_batches_tracked
backbone.enc.layer3.7.conv2.weight
backbone.enc.layer3.7.bn2.weight
backbone.enc.layer3.7.bn2.bias
backbone.enc.layer3.7.bn2.running_mean
backbone.enc.layer3.7.bn2.running_var
backbone.enc.layer3.7.bn2.num_batches_tracked
backbone.enc.layer3.7.conv3.weight
backbone.enc.layer3.7.bn3.weight
backbone.enc.layer3.7.bn3.bias
backbone.enc.layer3.7.bn3.running_mean
backbone.enc.layer3.7.bn3.running_var
backbone.enc.layer3.7.bn3.num_batches_tracked
backbone.enc.layer3.8.conv1.weight
backbone.enc.layer3.8.bn1.weight
backbone.enc.layer3.8.bn1.bias
backbone.enc.layer3.8.bn1.running_mean
backbone.enc.layer3.8.bn1.running_var
backbone.enc.layer3.8.bn1.num_batches_tracked
backbone.enc.layer3.8.conv2.weight
backbone.enc.layer3.8.bn2.weight
backbone.enc.layer3.8.bn2.bias
backbone.enc.layer3.8.bn2.running_mean
backbone.enc.layer3.8.bn2.running_var
backbone.enc.layer3.8.bn2.num_batches_tracked
backbone.enc.layer3.8.conv3.weight
backbone.enc.layer3.8.bn3.weight
backbone.enc.layer3.8.bn3.bias
backbone.enc.layer3.8.bn3.running_mean
backbone.enc.layer3.8.bn3.running_var
backbone.enc.layer3.8.bn3.num_batches_tracked
backbone.enc.layer3.9.conv1.weight
backbone.enc.layer3.9.bn1.weight
backbone.enc.layer3.9.bn1.bias
backbone.enc.layer3.9.bn1.running_mean
backbone.enc.layer3.9.bn1.running_var
backbone.enc.layer3.9.bn1.num_batches_tracked
backbone.enc.layer3.9.conv2.weight
backbone.enc.layer3.9.bn2.weight
backbone.enc.layer3.9.bn2.bias
backbone.enc.layer3.9.bn2.running_mean
backbone.enc.layer3.9.bn2.running_var
backbone.enc.layer3.9.bn2.num_batches_tracked
backbone.enc.layer3.9.conv3.weight
backbone.enc.layer3.9.bn3.weight
backbone.enc.layer3.9.bn3.bias
backbone.enc.layer3.9.bn3.running_mean
backbone.enc.layer3.9.bn3.running_var
backbone.enc.layer3.9.bn3.num_batches_tracked
backbone.enc.layer3.10.conv1.weight
backbone.enc.layer3.10.bn1.weight
backbone.enc.layer3.10.bn1.bias
backbone.enc.layer3.10.bn1.running_mean
backbone.enc.layer3.10.bn1.running_var
backbone.enc.layer3.10.bn1.num_batches_tracked
backbone.enc.layer3.10.conv2.weight
backbone.enc.layer3.10.bn2.weight
backbone.enc.layer3.10.bn2.bias
backbone.enc.layer3.10.bn2.running_mean
backbone.enc.layer3.10.bn2.running_var
backbone.enc.layer3.10.bn2.num_batches_tracked
backbone.enc.layer3.10.conv3.weight
backbone.enc.layer3.10.bn3.weight
backbone.enc.layer3.10.bn3.bias
backbone.enc.layer3.10.bn3.running_mean
backbone.enc.layer3.10.bn3.running_var
backbone.enc.layer3.10.bn3.num_batches_tracked
backbone.enc.layer3.11.conv1.weight
backbone.enc.layer3.11.bn1.weight
backbone.enc.layer3.11.bn1.bias
backbone.enc.layer3.11.bn1.running_mean
backbone.enc.layer3.11.bn1.running_var
backbone.enc.layer3.11.bn1.num_batches_tracked
backbone.enc.layer3.11.conv2.weight
backbone.enc.layer3.11.bn2.weight
backbone.enc.layer3.11.bn2.bias
backbone.enc.layer3.11.bn2.running_mean
backbone.enc.layer3.11.bn2.running_var
backbone.enc.layer3.11.bn2.num_batches_tracked
backbone.enc.layer3.11.conv3.weight
backbone.enc.layer3.11.bn3.weight
backbone.enc.layer3.11.bn3.bias
backbone.enc.layer3.11.bn3.running_mean
backbone.enc.layer3.11.bn3.running_var
backbone.enc.layer3.11.bn3.num_batches_tracked
backbone.enc.layer3.12.conv1.weight
backbone.enc.layer3.12.bn1.weight
backbone.enc.layer3.12.bn1.bias
backbone.enc.layer3.12.bn1.running_mean
backbone.enc.layer3.12.bn1.running_var
backbone.enc.layer3.12.bn1.num_batches_tracked
backbone.enc.layer3.12.conv2.weight
backbone.enc.layer3.12.bn2.weight
backbone.enc.layer3.12.bn2.bias
backbone.enc.layer3.12.bn2.running_mean
backbone.enc.layer3.12.bn2.running_var
backbone.enc.layer3.12.bn2.num_batches_tracked
backbone.enc.layer3.12.conv3.weight
backbone.enc.layer3.12.bn3.weight
backbone.enc.layer3.12.bn3.bias
backbone.enc.layer3.12.bn3.running_mean
backbone.enc.layer3.12.bn3.running_var
backbone.enc.layer3.12.bn3.num_batches_tracked
backbone.enc.layer3.13.conv1.weight
backbone.enc.layer3.13.bn1.weight
backbone.enc.layer3.13.bn1.bias
backbone.enc.layer3.13.bn1.running_mean
backbone.enc.layer3.13.bn1.running_var
backbone.enc.layer3.13.bn1.num_batches_tracked
backbone.enc.layer3.13.conv2.weight
backbone.enc.layer3.13.bn2.weight
backbone.enc.layer3.13.bn2.bias
backbone.enc.layer3.13.bn2.running_mean
backbone.enc.layer3.13.bn2.running_var
backbone.enc.layer3.13.bn2.num_batches_tracked
backbone.enc.layer3.13.conv3.weight
backbone.enc.layer3.13.bn3.weight
backbone.enc.layer3.13.bn3.bias
backbone.enc.layer3.13.bn3.running_mean
backbone.enc.layer3.13.bn3.running_var
backbone.enc.layer3.13.bn3.num_batches_tracked
backbone.enc.layer3.14.conv1.weight
backbone.enc.layer3.14.bn1.weight
backbone.enc.layer3.14.bn1.bias
backbone.enc.layer3.14.bn1.running_mean
backbone.enc.layer3.14.bn1.running_var
backbone.enc.layer3.14.bn1.num_batches_tracked
backbone.enc.layer3.14.conv2.weight
backbone.enc.layer3.14.bn2.weight
backbone.enc.layer3.14.bn2.bias
backbone.enc.layer3.14.bn2.running_mean
backbone.enc.layer3.14.bn2.running_var
backbone.enc.layer3.14.bn2.num_batches_tracked
backbone.enc.layer3.14.conv3.weight
backbone.enc.layer3.14.bn3.weight
backbone.enc.layer3.14.bn3.bias
backbone.enc.layer3.14.bn3.running_mean
backbone.enc.layer3.14.bn3.running_var
backbone.enc.layer3.14.bn3.num_batches_tracked
backbone.enc.layer3.15.conv1.weight
backbone.enc.layer3.15.bn1.weight
backbone.enc.layer3.15.bn1.bias
backbone.enc.layer3.15.bn1.running_mean
backbone.enc.layer3.15.bn1.running_var
backbone.enc.layer3.15.bn1.num_batches_tracked
backbone.enc.layer3.15.conv2.weight
backbone.enc.layer3.15.bn2.weight
backbone.enc.layer3.15.bn2.bias
backbone.enc.layer3.15.bn2.running_mean
backbone.enc.layer3.15.bn2.running_var
backbone.enc.layer3.15.bn2.num_batches_tracked
backbone.enc.layer3.15.conv3.weight
backbone.enc.layer3.15.bn3.weight
backbone.enc.layer3.15.bn3.bias
backbone.enc.layer3.15.bn3.running_mean
backbone.enc.layer3.15.bn3.running_var
backbone.enc.layer3.15.bn3.num_batches_tracked
backbone.enc.layer3.16.conv1.weight
backbone.enc.layer3.16.bn1.weight
backbone.enc.layer3.16.bn1.bias
backbone.enc.layer3.16.bn1.running_mean
backbone.enc.layer3.16.bn1.running_var
backbone.enc.layer3.16.bn1.num_batches_tracked
backbone.enc.layer3.16.conv2.weight
backbone.enc.layer3.16.bn2.weight
backbone.enc.layer3.16.bn2.bias
backbone.enc.layer3.16.bn2.running_mean
backbone.enc.layer3.16.bn2.running_var
backbone.enc.layer3.16.bn2.num_batches_tracked
backbone.enc.layer3.16.conv3.weight
backbone.enc.layer3.16.bn3.weight
backbone.enc.layer3.16.bn3.bias
backbone.enc.layer3.16.bn3.running_mean
backbone.enc.layer3.16.bn3.running_var
backbone.enc.layer3.16.bn3.num_batches_tracked
backbone.enc.layer3.17.conv1.weight
backbone.enc.layer3.17.bn1.weight
backbone.enc.layer3.17.bn1.bias
backbone.enc.layer3.17.bn1.running_mean
backbone.enc.layer3.17.bn1.running_var
backbone.enc.layer3.17.bn1.num_batches_tracked
backbone.enc.layer3.17.conv2.weight
backbone.enc.layer3.17.bn2.weight
backbone.enc.layer3.17.bn2.bias
backbone.enc.layer3.17.bn2.running_mean
backbone.enc.layer3.17.bn2.running_var
backbone.enc.layer3.17.bn2.num_batches_tracked
backbone.enc.layer3.17.conv3.weight
backbone.enc.layer3.17.bn3.weight
backbone.enc.layer3.17.bn3.bias
backbone.enc.layer3.17.bn3.running_mean
backbone.enc.layer3.17.bn3.running_var
backbone.enc.layer3.17.bn3.num_batches_tracked
backbone.enc.layer3.18.conv1.weight
backbone.enc.layer3.18.bn1.weight
backbone.enc.layer3.18.bn1.bias
backbone.enc.layer3.18.bn1.running_mean
backbone.enc.layer3.18.bn1.running_var
backbone.enc.layer3.18.bn1.num_batches_tracked
backbone.enc.layer3.18.conv2.weight
backbone.enc.layer3.18.bn2.weight
backbone.enc.layer3.18.bn2.bias
backbone.enc.layer3.18.bn2.running_mean
backbone.enc.layer3.18.bn2.running_var
backbone.enc.layer3.18.bn2.num_batches_tracked
backbone.enc.layer3.18.conv3.weight
backbone.enc.layer3.18.bn3.weight
backbone.enc.layer3.18.bn3.bias
backbone.enc.layer3.18.bn3.running_mean
backbone.enc.layer3.18.bn3.running_var
backbone.enc.layer3.18.bn3.num_batches_tracked
backbone.enc.layer3.19.conv1.weight
backbone.enc.layer3.19.bn1.weight
backbone.enc.layer3.19.bn1.bias
backbone.enc.layer3.19.bn1.running_mean
backbone.enc.layer3.19.bn1.running_var
backbone.enc.layer3.19.bn1.num_batches_tracked
backbone.enc.layer3.19.conv2.weight
backbone.enc.layer3.19.bn2.weight
backbone.enc.layer3.19.bn2.bias
backbone.enc.layer3.19.bn2.running_mean
backbone.enc.layer3.19.bn2.running_var
backbone.enc.layer3.19.bn2.num_batches_tracked
backbone.enc.layer3.19.conv3.weight
backbone.enc.layer3.19.bn3.weight
backbone.enc.layer3.19.bn3.bias
backbone.enc.layer3.19.bn3.running_mean
backbone.enc.layer3.19.bn3.running_var
backbone.enc.layer3.19.bn3.num_batches_tracked
backbone.enc.layer3.20.conv1.weight
backbone.enc.layer3.20.bn1.weight
backbone.enc.layer3.20.bn1.bias
backbone.enc.layer3.20.bn1.running_mean
backbone.enc.layer3.20.bn1.running_var
backbone.enc.layer3.20.bn1.num_batches_tracked
backbone.enc.layer3.20.conv2.weight
backbone.enc.layer3.20.bn2.weight
backbone.enc.layer3.20.bn2.bias
backbone.enc.layer3.20.bn2.running_mean
backbone.enc.layer3.20.bn2.running_var
backbone.enc.layer3.20.bn2.num_batches_tracked
backbone.enc.layer3.20.conv3.weight
backbone.enc.layer3.20.bn3.weight
backbone.enc.layer3.20.bn3.bias
backbone.enc.layer3.20.bn3.running_mean
backbone.enc.layer3.20.bn3.running_var
backbone.enc.layer3.20.bn3.num_batches_tracked
backbone.enc.layer3.21.conv1.weight
backbone.enc.layer3.21.bn1.weight
backbone.enc.layer3.21.bn1.bias
backbone.enc.layer3.21.bn1.running_mean
backbone.enc.layer3.21.bn1.running_var
backbone.enc.layer3.21.bn1.num_batches_tracked
backbone.enc.layer3.21.conv2.weight
backbone.enc.layer3.21.bn2.weight
backbone.enc.layer3.21.bn2.bias
backbone.enc.layer3.21.bn2.running_mean
backbone.enc.layer3.21.bn2.running_var
backbone.enc.layer3.21.bn2.num_batches_tracked
backbone.enc.layer3.21.conv3.weight
backbone.enc.layer3.21.bn3.weight
backbone.enc.layer3.21.bn3.bias
backbone.enc.layer3.21.bn3.running_mean
backbone.enc.layer3.21.bn3.running_var
backbone.enc.layer3.21.bn3.num_batches_tracked
backbone.enc.layer3.22.conv1.weight
backbone.enc.layer3.22.bn1.weight
backbone.enc.layer3.22.bn1.bias
backbone.enc.layer3.22.bn1.running_mean
backbone.enc.layer3.22.bn1.running_var
backbone.enc.layer3.22.bn1.num_batches_tracked
backbone.enc.layer3.22.conv2.weight
backbone.enc.layer3.22.bn2.weight
backbone.enc.layer3.22.bn2.bias
backbone.enc.layer3.22.bn2.running_mean
backbone.enc.layer3.22.bn2.running_var
backbone.enc.layer3.22.bn2.num_batches_tracked
backbone.enc.layer3.22.conv3.weight
backbone.enc.layer3.22.bn3.weight
backbone.enc.layer3.22.bn3.bias
backbone.enc.layer3.22.bn3.running_mean
backbone.enc.layer3.22.bn3.running_var
backbone.enc.layer3.22.bn3.num_batches_tracked

----------------------------------------------------------
And Vb are:
backbone.enc.layer4.0.conv1.weight
backbone.enc.layer4.0.bn1.weight
backbone.enc.layer4.0.bn1.bias
backbone.enc.layer4.0.bn1.running_mean
backbone.enc.layer4.0.bn1.running_var
backbone.enc.layer4.0.bn1.num_batches_tracked
backbone.enc.layer4.0.conv2.weight
backbone.enc.layer4.0.bn2.weight
backbone.enc.layer4.0.bn2.bias
backbone.enc.layer4.0.bn2.running_mean
backbone.enc.layer4.0.bn2.running_var
backbone.enc.layer4.0.bn2.num_batches_tracked
backbone.enc.layer4.0.conv3.weight
backbone.enc.layer4.0.bn3.weight
backbone.enc.layer4.0.bn3.bias
backbone.enc.layer4.0.bn3.running_mean
backbone.enc.layer4.0.bn3.running_var
backbone.enc.layer4.0.bn3.num_batches_tracked
backbone.enc.layer4.0.downsample.0.weight
backbone.enc.layer4.0.downsample.1.weight
backbone.enc.layer4.0.downsample.1.bias
backbone.enc.layer4.0.downsample.1.running_mean
backbone.enc.layer4.0.downsample.1.running_var
backbone.enc.layer4.0.downsample.1.num_batches_tracked
backbone.enc.layer4.1.conv1.weight
backbone.enc.layer4.1.bn1.weight
backbone.enc.layer4.1.bn1.bias
backbone.enc.layer4.1.bn1.running_mean
backbone.enc.layer4.1.bn1.running_var
backbone.enc.layer4.1.bn1.num_batches_tracked
backbone.enc.layer4.1.conv2.weight
backbone.enc.layer4.1.bn2.weight
backbone.enc.layer4.1.bn2.bias
backbone.enc.layer4.1.bn2.running_mean
backbone.enc.layer4.1.bn2.running_var
backbone.enc.layer4.1.bn2.num_batches_tracked
backbone.enc.layer4.1.conv3.weight
backbone.enc.layer4.1.bn3.weight
backbone.enc.layer4.1.bn3.bias
backbone.enc.layer4.1.bn3.running_mean
backbone.enc.layer4.1.bn3.running_var
backbone.enc.layer4.1.bn3.num_batches_tracked
backbone.enc.layer4.2.conv1.weight
backbone.enc.layer4.2.bn1.weight
backbone.enc.layer4.2.bn1.bias
backbone.enc.layer4.2.bn1.running_mean
backbone.enc.layer4.2.bn1.running_var
backbone.enc.layer4.2.bn1.num_batches_tracked
backbone.enc.layer4.2.conv2.weight
backbone.enc.layer4.2.bn2.weight
backbone.enc.layer4.2.bn2.bias
backbone.enc.layer4.2.bn2.running_mean
backbone.enc.layer4.2.bn2.running_var
backbone.enc.layer4.2.bn2.num_batches_tracked
backbone.enc.layer4.2.conv3.weight
backbone.enc.layer4.2.bn3.weight
backbone.enc.layer4.2.bn3.bias
backbone.enc.layer4.2.bn3.running_mean
backbone.enc.layer4.2.bn3.running_var
backbone.enc.layer4.2.bn3.num_batches_tracked
backbone.enc.attnpool.positional_embedding
backbone.enc.attnpool.k_proj.weight
backbone.enc.attnpool.k_proj.bias
backbone.enc.attnpool.q_proj.weight
backbone.enc.attnpool.q_proj.bias
backbone.enc.attnpool.v_proj.weight
backbone.enc.attnpool.v_proj.bias
backbone.enc.attnpool.c_proj.weight
backbone.enc.attnpool.c_proj.bias

is this correct or am i missing something?

Thanks for your time and consideration.

**Comment by vidit09** [comment]
Yes, you are correct. Va until 3 and Vb until 4 + attn layers

**Comment by ParthT25** [comment]
Okay, Thank you soo much for the response
