### ISSUE TITLE
Global attention pooling

### ISSUE THREAD

**Issue by ParthT25** [vidit09/domaingen#13]
Hello,

can you please provide some info about the global attention pooling in the backbone.
![image](https://github.com/vidit09/domaingen/assets/62347615/c755401a-a516-46b4-9b81-ee02ec42abbd)
what does this code do?
and where is the implementation of this pooling?

**Comment by vidit09** [comment]
Hello 
The attnpool is a self-attention-based pooling operation added to the ResNet architecture in the original CLIP training.  We keep this layer and initialize with [CLIP pretrained weights](https://github.com/vidit09/domaingen)

**Comment by ParthT25** [comment]
Hello vidit,
sorry for bothering you but i have one more question to ask.
If i wanted to add augmentations  during inference then what changes do i need to make?

thanks for your time.

**Comment by vidit09** [comment]
Hello , 

You can pass a dataset mapper function [here](https://github.com/vidit09/domaingen/blob/9c03d07a6f8c12b6a7a5e02bd9346d7bb5a3b9ff/train.py#L564) as mentioned in [documentation](https://detectron2.readthedocs.io/en/latest/modules/data.html#:~:text=none%20is%20available.-,detectron2,-.data.build_detection_test_loader) of detectron2.  There is an example in the [code](https://github.com/vidit09/domaingen/blob/9c03d07a6f8c12b6a7a5e02bd9346d7bb5a3b9ff/train.py#L66) as well.

**Comment by ParthT25** [comment]
Sorry to bother you,

Just one more thing how exactly the bbox prediction is done?
![image](https://github.com/vidit09/domaingen/assets/62347615/6da145e7-8ee2-41fd-a25d-cb90d397f1fd)
Here the input feature size is 2048 and output is 28.
28 i understant that it is 7x4 for 7 classes and xmin,ymin,H,W but what about 2048?
the ROIs are of size 2048x7x7 right?
so is there any channel wise averaging?

Your response would be really helpful

**Comment by vidit09** [comment]
Yes the averaging happens in spatial dimension to get 2048-dim vectors for each RoI

**Comment by ParthT25** [comment]
I'm currently exploring integrating zero-shot object detection into your project. I've made some headway with classifying the regions of interest (ROIs), but I'm facing uncertainty regarding the bounding box (bbox) prediction. In the standard Faster R-CNN approach, the bbox predictor is consistent across all classes, but here it's handled differently.

Do you have any insights or suggestions on how to tackle this aspect effectively? Your input would be greatly appreciated.

**Comment by ParthT25** [comment]
And i wanted to enable offsets(Learned during optimization step for DG) during inference,
is there anyway to do that?

**Comment by vidit09** [comment]
you'll need to modify the condition check for this [line](https://github.com/vidit09/domaingen/blob/9c03d07a6f8c12b6a7a5e02bd9346d7bb5a3b9ff/train.py#L302)

**Comment by ParthT25** [comment]
Satisfied
