### ISSUE TITLE
Eq.4 has some issues

### ISSUE THREAD

**Issue by EighteenStop** [vidit09/domaingen#14]
Eq.4 doesn't seem to be an expression for cosine distance.
![微信截图_20240313173514](https://github.com/vidit09/domaingen/assets/163286407/d6dd4bd4-aace-4c6f-9831-fd34adc648e4)

**Comment by vidit09** [comment]
Hello, 
Sorry for the mistake. It somehow went unnoticed by us in the paper. In the [code](https://github.com/vidit09/domaingen/blob/9c03d07a6f8c12b6a7a5e02bd9346d7bb5a3b9ff/modeling/meta_arch.py#L283), we use proper cosine distance as 1-dot_product between two normalized vectors.

**Comment by EighteenStop** [comment]
Thank you for your answer. This paper is great.
