### ISSUE TITLE
Question about Semantic Augmentation

### ISSUE THREAD

**Issue by luoluo123123123123** [vidit09/domaingen#19]
I‘m confused that,if we can consider
![image](https://github.com/vidit09/domaingen/assets/123624781/72fb83ae-aac9-4e2a-a032-78532439e897) as target image embedding，why we need to train Aj？

why not just add 
![image](https://github.com/vidit09/domaingen/assets/123624781/19dd90c5-38dc-4b53-b9a4-d5ccccb2309c)
to Training Step？
by the way，How much memory is needed to run this experiment in your setting？I would greatly appreciate any assistance you can provide.

**Comment by vidit09** [comment]
Hello, 
The goal of $A_j$ is to meaningfully translate the feature embeddings. We wanted all the trainable blocks like RPN , final bbox Classifier, and regressors to use these translated features.   

We used 1 A100 GPU with 40GB VRAM in all the experiments.

**Comment by luoluo123123123123** [comment]
![image](https://github.com/vidit09/domaingen/assets/123624781/1f85dd97-0ff0-486a-9b30-9b0a9a613bcb)
That means we can not do augmentation like this?

**Comment by luoluo123123123123** [comment]
I would like to know, what is the difference between directly subtracting the words 'rain' and 'sunny' as augmentation, and translating them into Aj? I appreciate your assistance on this matter.

**Comment by vidit09** [comment]
so the output of $\mathcal{V}^b$ corresponds to the final 512-dimensional clip embedding,  $\mathcal{V}^a$ is hxwx1024 matrix, hence it is not straightforward to map to clip embedding space there

**Comment by luoluo123123123123** [comment]
Thank you for your explanation; I completely understand now! One last question ：If I use the Vit-B/16 pre-trained CLIP model as the text encoder and the ImageNet RN101 pre-trained model as the image encoder, would this approach be effective?

**Comment by luoluo123123123123** [comment]
Thank you for your explanation; I completely understand now! One last question ：If I use the Vit-B/16 pre-trained CLIP model as the text encoder and the ImageNet RN101 pre-trained model as the image encoder, would this approach be effective? Is this method only applicable when the source of the image encoder and text encoder is consistent?

**Comment by vidit09** [comment]
From my understanding underlying Clip text encoder architecture i.e GPT2 is the same for ViTb16 or RN101, which are image encoders. In any case, I think consistency might be needed

**Comment by luoluo123123123123** [comment]
Thank you for the detailed explanation. Your insights are very helpful and enlightening!

**Comment by luoluo123123123123** [comment]
Thank you for the detailed explanation. Your insights are very helpful and enlightening!
