### ISSUE TITLE
Iterative epoch for Semantic Augmentation

### ISSUE THREAD

**Issue by joy-peng** [vidit09/domaingen#22]
Hi, can you please tell me about the Semantic Augmentation obtaining whether it is enough to traverse all the day images just once or does it need to be traversed many times similar to the use of epoch=50?

**Comment by vidit09** [comment]
Hello, 
if i get your question correctly, no you don't have to see all the day images to get the augmentations, we optimize only 1000 iterations

**Comment by joy-peng** [comment]
Your answer solved my confusion perfectly, thanks a lot!
