### ISSUE TITLE
Save model  issue

### ISSUE THREAD

**Issue by ygjwd12345** [vidit09/domaingen#3]
When I run your code, I face a problem:
‘’‘
Traceback (most recent call last):
  File "/home/gyang/data/domaingen/detectron2/detectron2/engine/train_loop.py", line 156, in train
    self.after_step()
  File "/home/gyang/data/domaingen/detectron2/detectron2/engine/train_loop.py", line 190, in after_step
    h.after_step()
  File "/home/gyang/data/domaingen/detectron2/detectron2/engine/hooks.py", line 299, in after_step
    self._best_checking()
  File "/home/gyang/data/domaingen/detectron2/detectron2/engine/hooks.py", line 272, in _best_checking
    self._checkpointer.save(f"{self._file_prefix}", **additional_state)
  File "/home/gyang/anaconda3/envs/det2/lib/python3.10/site-packages/fvcore/common/checkpoint.py", line 118, in save
    data[key] = obj.state_dict()
  File "/home/gyang/data/domaingen/train.py", line 429, in state_dict
    ret = super().state_dict()
  File "/home/gyang/data/domaingen/detectron2/detectron2/engine/defaults.py", line 498, in state_dict
    ret["_trainer"] = self._trainer.state_dict()
  File "/home/gyang/data/domaingen/detectron2/detectron2/engine/train_loop.py", line 425, in state_dict
    ret["optimizer"] = self.optimizer.state_dict()
AttributeError: 'tuple' object has no attribute 'state_dict'
’‘’
I am green for detection, would you mind give me some suggestion to fix this bug?

**Comment by ygjwd12345** [comment]
I have fixed this bug. Now I have another question: can you provide val.py?

**Comment by vidit09** [comment]
Hello @ygjwd12345 , thanks for your interest. You can run the evaluation with following command
`python train.py --eval-only --config-file <path to the file.yaml> MODEL.WEIGHTS <path to the weight.pth>`

**Comment by ygjwd12345** [comment]
Yes, for your reply. 
Follow above command, it just evaluates  daytime_clear_test.
like
![image](https://github.com/vidit09/domaingen/assets/32895754/df14b652-0283-419c-81d3-cb7eeacdf4ba)
How can I get result like Tab 1 ?
![image](https://github.com/vidit09/domaingen/assets/32895754/23411b90-4f50-46bb-9dcf-1904a9ebfae3)
or Tab 2?
![image](https://github.com/vidit09/domaingen/assets/32895754/16ea6ca3-0d0b-411d-a67f-0fe2ef0f053f)

**Comment by vidit09** [comment]
You can pass the dataset to evaluate as a command line arg 

`DATASETS.TEST "('daytime_foggy_test','night_sunny_test','night_rainy_train','dusk_rainy_train',)"` 

or change the [yaml file](https://github.com/vidit09/domaingen/blob/main/configs/diverse_weather.yaml#L4) itself to include all the datasets. 

Classwise APs are printed in the log itself, see line 5 from the bottom in your added image. 

![Screenshot 2023-09-09 at 13 50 31](https://github.com/vidit09/domaingen/assets/15695152/2e0bc000-46e5-4ed3-927a-2a74cc46043f)

**Comment by ygjwd12345** [comment]
I rerun the code with bs=2  because I just have 4090
the result is a little bit lower than report
![image](https://github.com/vidit09/domaingen/assets/32895754/e06e627c-4cf3-4355-ab51-759bb0f93d52)
would you mind giving me suggestion?

**Comment by vidit09** [comment]
maybe, you can try running it for a longer number of iterations as the batch size has reduced, and potentially tuning the learning rate can be useful

**Comment by ygjwd12345** [comment]
Thanks for your suggestion I am working on it

**Comment by vidit09** [comment]
Closing it now

**Comment by Hayoung93** [comment]
@ygjwd12345 , How did you fixed the error?
I'd met the same one and changed `ret["optimizer"] = self.optimizer.state_dict()` to `ret["optimizer1"] = self.optimizer[0].state_dict(); ret["optimizer2"] = self.optimizer[1].state_dict()` in `detectron2/engine/train_loop.py` and it seems okay for now. Can you share your solution? Thanks.

**Comment by ygjwd12345** [comment]
> @ygjwd12345 , How did you fixed the error? I'd met the same one and changed `ret["optimizer"] = self.optimizer.state_dict()` to `ret["optimizer1"] = self.optimizer[0].state_dict(); ret["optimizer2"] = self.optimizer[1].state_dict()` in `detectron2/engine/train_loop.py` and it seems okay for now. Can you share your solution? Thanks.

Maybe I use ChatGPT for debug.

**Comment by xinxuand** [comment]
@vidit09 Hello, I also encountered this problem, how did you solve it?
Traceback (most recent call last):
  File "/root/detectron2/detectron2/engine/train_loop.py", line 150, in train
    self.after_step()
  File "/root/detectron2/detectron2/engine/train_loop.py", line 180, in after_step
    h.after_step()
  File "/root/detectron2/detectron2/engine/hooks.py", line 298, in after_step
    self._best_checking()
  File "/root/detectron2/detectron2/engine/hooks.py", line 271, in _best_checking
    self._checkpointer.save(f"{self._file_prefix}", **additional_state)
  File "/root/miniconda3/lib/python3.8/site-packages/fvcore/common/checkpoint.py", line 118, in save
    data[key] = obj.state_dict()
  File "/root/domaingen-main/train.py", line 429, in state_dict
    ret = super().state_dict()
  File "/root/detectron2/detectron2/engine/defaults.py", line 498, in state_dict
    ret["_trainer"] = self._trainer.state_dict()
  File "/root/detectron2/detectron2/engine/train_loop.py", line 367, in state_dict
    ret["optimizer"] = self.optimizer.state_dict()
AttributeError: 'tuple' object has no attribute 'state_dict'

**Comment by xinxuand** [comment]
@ygjwd12345 Hello, I also encountered this problem, how did you solve it?

**Comment by vidit09** [comment]
> > @ygjwd12345 , How did you fixed the error? I'd met the same one and changed `ret["optimizer"] = self.optimizer.state_dict()` to `ret["optimizer1"] = self.optimizer[0].state_dict(); ret["optimizer2"] = self.optimizer[1].state_dict()` in `detectron2/engine/train_loop.py` and it seems okay for now. Can you share your solution? Thanks.
> 
> Maybe I use ChatGPT for debug.

You need to change the code to index optimizers state_dicts

**Comment by xinxuand** [comment]
@vidit09 Can you be more detailed? Thank you very much.

**Comment by Lybnn** [comment]
@vidit09 Hello, I also encountered this problem:AttributeError: 'tuple' object has no attribute 'state_dict'.How did you fixed the error?Can you be more detailed? Thank you very much.

**Comment by vidit09** [comment]
> /root/detectron2/detectron2/engine/train_loop.py line 367

please update this line with the  mentioned change

**Comment by xinxuand** [comment]
Hello, the result I got when evaluating the daytime_clear is this, it seems to be very different from the paper, I don't know why?
![微信截图_20240409000615](https://github.com/vidit09/domaingen/assets/130667445/c1fee630-ef02-4cbb-971c-774d1817450f)

**Comment by fengjingchehu** [comment]
> 您好，我在评估daytime_clear时得到的结果是这样的，它似乎与论文有很大不同，我不知道为什么？ ![微信截图_20240409000615](https://private-user-images.githubusercontent.com/130667445/320568351-c1fee630-ef02-4cbb-971c-774d1817450f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MjQ2MDksIm5iZiI6MTcyMTkyNDMwOSwicGF0aCI6Ii8xMzA2Njc0NDUvMzIwNTY4MzUxLWMxZmVlNjMwLWVmMDItNGNiYi05NzFjLTc3NGQxODE3NDUwZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNVQxNjE4MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNjcwMGYzYzJiOWI0MmY0YTg5YTkyMDVhZGQ4NGFlNWNiNmY3YTQ3NDg3ZWVkYjQxZDFhNDFhN2VkYjE1MmJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Mew1T3BGzOSR5M-s-OI3ODAn8EmrT8auvAK50iP-SPE)
I got similar results. Did you end up solving it?

**Comment by vidit09** [comment]
could it be similar to this [issue](https://github.com/vidit09/domaingen/issues/2#issuecomment-1700856024)?
