### ISSUE TITLE
About The results.

### ISSUE THREAD

**Issue by BCXNSD** [vidit09/domaingen#31]
![image](https://github.com/user-attachments/assets/2cf84b8d-8ee4-4505-bbb1-098479da4ceb)
Hello
I want to ask the single-domain generalization result was evaluated on which dataset part. Such as Night Rainy dataset, is the result evaluated on the test set or train set, or on the entire dataset? If it was evaluated on test set, However there are no "test.txt" on the ImageSets path. But when register dataset, we need concat train or test text with the dataset name, it may not be possible to read the dataset.

**Comment by vidit09** [comment]
Hello ,
it was on the train set as no test split was provided by SDGOD at the time.

**Comment by BCXNSD** [comment]
> Hello , it was on the train set as no test split was provided by SDGOD at the time.

OK, thanks a lot.
