### ISSUE TITLE
Question about Matching Feature Dimensions with Pre-trained CLIP Weights in Training

### ISSUE THREAD

**Issue by pzhhhhh2263** [vidit09/domaingen#33]
Thank you for your excellent work.

 I am currently exploring your code related to semantic enhancement and have encountered a technical issue that I am struggling to understand. For matching the pre-trained weights from CLIP, you chose to use 224x224 sized images for image feature extraction, and the offsets have been preset to a size of 14x14. This size matches the downsampling scale to the 'res4' stage perfectly when using 224x224 images. However, the paper mentions using images of size 600 × 1067 for training, which, logically, would not downsample to a size compatible with a direct addition to the 14x14 offsets.

Could you please clarify how this discrepancy in feature map sizes is addressed during training? This seems to be a critical point for ensuring the effectiveness of the model, especially when integrating features with pre-trained dimensions from different image resolutions.

Thank you for your time and assistance.

**Comment by vidit09** [comment]
Thank you for your interest. Yes this discrepancy has been addressed in section 3.3 of the paper and the same is reflected in the codebase.

**Comment by pzhhhhh2263** [comment]
Thank you for your prompt response, which resolved my doubts
