### ISSUE TITLE
Reagarding Training the model excluding one class

### ISSUE THREAD

**Issue by ParthT25** [vidit09/domaingen#9]
Hello vidit,
I am working on zero shot object detection and i wanted to train your model while excluding one class for ex. bus and then try to to detect bus using ZSL.

can you please guide me how to modify the code so that bus is no longer considered while training.
PS:I have deleted bus objects from the XML files.

**Comment by vidit09** [comment]
Hello @papz2000 ,
You will have to change the number of classes from 7 to 6 in the diverse_weather.yaml [file](https://github.com/vidit09/domaingen/blob/9c03d07a6f8c12b6a7a5e02bd9346d7bb5a3b9ff/configs/diverse_weather.yaml#L32) and delete the entry for _bus_ from [here](https://github.com/vidit09/domaingen/blob/9c03d07a6f8c12b6a7a5e02bd9346d7bb5a3b9ff/data/datasets/diverse_weather.py#L15)

**Comment by ParthT25** [comment]
Thanks for your work and the response,
I have kept the model for training successfully.
